In [10]:
import matplotlib.pyplot as plt
import pandas as pd

from IPython.display import set_matplotlib_formats
%matplotlib inline
set_matplotlib_formats('svg')

pd.options.display.max_columns = None

In [11]:
census = pd.read_csv('./acs2015_county_data.csv')
census.head()

,CensusId,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,Asian,Pacific,Citizen,Income,IncomeErr,IncomePerCap,IncomePerCapErr,Poverty,ChildPoverty,Professional,Service,Office,Construction,Production,Drive,Carpool,Transit,Walk,OtherTransp,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment
0,1001,Alabama,Autauga,55221,26745,28476,2.6,75.8,18.5,0.4,1.0,0.0,40725,51281.0,2391.0,24974,1080,12.9,18.6,33.2,17.0,24.2,8.6,17.1,87.5,8.8,0.1,0.5,1.3,1.8,26.5,23986,73.6,20.9,5.5,0.0,7.6
1,1003,Alabama,Baldwin,195121,95314,99807,4.5,83.1,9.5,0.6,0.7,0.0,147695,50254.0,1263.0,27317,711,13.4,19.2,33.1,17.7,27.1,10.8,11.2,84.7,8.8,0.1,1.0,1.4,3.9,26.4,85953,81.5,12.3,5.8,0.4,7.5
2,1005,Alabama,Barbour,26932,14497,12435,4.6,46.2,46.7,0.2,0.4,0.0,20714,32964.0,2973.0,16824,798,26.7,45.3,26.8,16.1,23.1,10.8,23.1,83.8,10.9,0.4,1.8,1.5,1.6,24.1,8597,71.8,20.8,7.3,0.1,17.6
3,1007,Alabama,Bibb,22604,12073,10531,2.2,74.5,21.4,0.4,0.1,0.0,17495,38678.0,3995.0,18431,1618,16.8,27.9,21.5,17.9,17.8,19.0,23.7,83.2,13.5,0.5,0.6,1.5,0.7,28.8,8294,76.8,16.1,6.7,0.4,8.3
4,1009,Alabama,Blount,57710,28512,29198,8.6,87.9,1.5,0.3,0.1,0.0,42345,45813.0,3141.0,20532,708,16.7,27.2,28.5,14.1,23.9,13.5,19.9,84.9,11.2,0.4,0.9,0.4,2.3,34.9,22189,82.0,13.5,4.2,0.4,7.7

In [12]:
census.describe()

,CensusId,TotalPop,Men,Women,Hispanic,White,Black,Native,Asian,Pacific,Citizen,Income,IncomeErr,IncomePerCap,IncomePerCapErr,Poverty,ChildPoverty,Professional,Service,Office,Construction,Production,Drive,Carpool,Transit,Walk,OtherTransp,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment
count,3220.000000,3.220000e+03,3.220000e+03,3.220000e+03,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3.220000e+03,3219.000000,3219.000000,3220.000000,3220.000000,3220.000000,3219.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3.220000e+03,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000
mean,31393.605280,9.940935e+04,4.889694e+04,5.051241e+04,11.011522,75.428789,8.665497,1.723509,1.229068,0.082733,6.993507e+04,46129.868903,2850.395464,23981.771739,1362.518944,17.493261,24.180801,30.990621,18.346398,22.215807,12.714099,15.733385,79.181925,10.278758,0.971832,3.323509,1.612733,4.631770,23.278758,4.559352e+04,74.219348,17.560870,7.931801,0.288106,8.094441
std,16292.078954,3.193055e+05,1.566813e+05,1.626620e+05,19.241380,22.932890,14.279122,7.253115,2.633079,0.734931,2.051189e+05,12911.297940,1918.942273,6204.339960,1049.875689,8.317883,11.698329,6.368379,3.635764,3.199682,4.216784,5.736308,7.657972,2.907897,3.059019,3.756096,1.670988,3.178772,5.600466,1.496995e+05,7.863188,6.510354,3.914974,0.455137,4.096114
min,1001.000000,8.500000e+01,4.200000e+01,4.300000e+01,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000e+01,10499.000000,270.000000,5878.000000,113.000000,1.400000,0.000000,13.500000,5.000000,4.100000,1.700000,0.000000,5.200000,0.000000,0.000000,0.000000,0.000000,0.000000,4.900000,6.200000e+01,25.000000,5.800000,0.000000,0.000000,0.000000
25%,19032.500000,1.121800e+04,5.637250e+03,5.572000e+03,1.900000,64.100000,0.500000,0.100000,0.200000,0.000000,8.450500e+03,38191.500000,1635.000000,20238.500000,755.000000,12.100000,16.300000,26.700000,16.000000,20.200000,9.800000,11.500000,76.600000,8.400000,0.100000,1.400000,0.900000,2.700000,19.500000,4.550750e+03,70.500000,13.100000,5.400000,0.100000,5.500000
50%,30024.000000,2.603500e+04,1.293200e+04,1.305700e+04,3.900000,84.100000,1.900000,0.300000,0.500000,0.000000,1.964300e+04,44749.000000,2406.000000,23460.000000,1096.500000,16.150000,22.700000,29.900000,18.100000,22.400000,12.100000,15.250000,80.700000,9.900000,0.400000,2.400000,1.300000,3.900000,23.000000,1.050800e+04,75.700000,16.200000,6.900000,0.200000,7.600000
75%,46105.500000,6.643050e+04,3.299275e+04,3.348750e+04,9.825000,93.200000,9.600000,0.600000,1.200000,0.000000,4.992050e+04,52074.000000,3446.000000,27053.250000,1631.000000,20.700000,30.000000,34.400000,20.300000,24.400000,14.900000,19.325000,83.700000,11.800000,0.800000,4.000000,1.900000,5.600000,26.800000,2.863275e+04,79.700000,20.500000,9.400000,0.300000,9.900000
max,72153.000000,1.003839e+07,4.945351e+06,5.093037e+06,99.900000,99.800000,85.900000,92.100000,41.600000,35.300000,6.046749e+06,123453.000000,21355.000000,65600.000000,15266.000000,64.200000,81.600000,74.000000,38.200000,35.400000,40.300000,55.600000,94.600000,29.900000,61.700000,71.200000,39.100000,37.200000,44.000000,4.635465e+06,88.300000,66.200000,36.600000,9.800000,36.500000

In [13]:
census.isnull().sum(axis = 0)

CensusId           0
State              0
County             0
TotalPop           0
Men                0
Women              0
Hispanic           0
White              0
Black              0
Native             0
Asian              0
Pacific            0
Citizen            0
Income             1
IncomeErr          1
IncomePerCap       0
IncomePerCapErr    0
Poverty            0
ChildPoverty       1
Professional       0
Service            0
Office             0
Construction       0
Production         0
Drive              0
Carpool            0
Transit            0
Walk               0
OtherTransp        0
WorkAtHome         0
MeanCommute        0
Employed           0
PrivateWork        0
PublicWork         0
SelfEmployed       0
FamilyWork         0
Unemployment       0
dtype: int64

In [14]:
census_missing = census.dropna()

In [15]:
census_columns = [col for col in census.columns.values if col not in ['CensusId', 'State', 'County']]

# K-Means

In [33]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=4)

In [34]:
census_clusters = kmeans.fit(census_missing[census_columns])

# really difficult to plot (34-dimensional space)
census_clusters.cluster_centers_

array([[4.91636213e+04, 2.43276000e+04, 2.48360213e+04, 1.05735632e+01,
        7.64456486e+01, 8.37155993e+00, 1.79891626e+00, 9.33431856e-01,
        6.59113300e-02, 3.63820558e+04, 4.52640923e+04, 2.96395468e+03,
        2.35384269e+04, 1.41439048e+03, 1.76698851e+01, 2.44180296e+01,
        3.05360263e+01, 1.83735304e+01, 2.20772085e+01, 1.29872250e+01,
        1.60262726e+01, 7.94217077e+01, 1.03420033e+01, 6.63908046e-01,
        3.34440066e+00, 1.59431856e+00, 4.63448276e+00, 2.30822660e+01,
        2.17587507e+04, 7.38585878e+01, 1.77766174e+01, 8.06781609e+00,
        2.96748768e-01, 8.08042693e+00],
       [2.59497053e+06, 1.27467168e+06, 1.32029884e+06, 3.28736842e+01,
        3.98684211e+01, 1.44368421e+01, 3.31578947e-01, 9.75789474e+00,
        1.89473684e-01, 1.65020984e+06, 5.85898947e+04, 4.97473684e+02,
        3.08353158e+04, 2.48105263e+02, 1.68368421e+01, 2.35842105e+01,
        3.71842105e+01, 1.95105263e+01, 2.45473684e+01, 8.02631579e+00,
        1.07368421e+01, 6.73736842e+01, 9.48947368e+00, 1.28210526e+01,
        3.63684211e+00, 2.17894737e+00, 4.51052632e+00, 2.92157895e+01,
        1.20507611e+06, 8.17000000e+01, 1.18947368e+01, 6.28421053e+00,
        1.36842105e-01, 9.23157895e+00],
       [7.25829000e+05, 3.54289993e+05, 3.71539007e+05, 1.66542484e+01,
        6.03967320e+01, 1.39163399e+01, 3.44444444e-01, 5.84771242e+00,
        1.73856209e-01, 5.03311484e+05, 6.16159020e+04, 8.53267974e+02,
        3.17643203e+04, 3.96555556e+02, 1.39954248e+01, 1.96810458e+01,
        3.92908497e+01, 1.75960784e+01, 2.46052288e+01, 7.99673203e+00,
        1.05111111e+01, 7.63058824e+01, 9.13202614e+00, 5.60326797e+00,
        2.59934641e+00, 1.82810458e+00, 4.52549020e+00, 2.64862745e+01,
        3.46560105e+05, 8.07816993e+01, 1.36418301e+01, 5.44183007e+00,
        1.39215686e-01, 8.22679739e+00],
       [1.00383880e+07, 4.94535100e+06, 5.09303700e+06, 4.82000000e+01,
        2.69000000e+01, 8.00000000e+00, 2.00000000e-01, 1.40000000e+01,
        2.00000000e-01, 6.04674900e+06, 5.61960000e+04, 2.70000000e+02,
        2.83370000e+04, 1.13000000e+02, 1.82000000e+01, 2.58000000e+01,
        3.57000000e+01, 1.91000000e+01, 2.46000000e+01, 7.80000000e+00,
        1.28000000e+01, 7.30000000e+01, 9.90000000e+00, 6.80000000e+00,
        2.80000000e+00, 2.30000000e+00, 5.10000000e+00, 3.00000000e+01,
        4.63546500e+06, 7.90000000e+01, 1.15000000e+01, 9.40000000e+00,
        2.00000000e-01, 1.00000000e+01]])

In [35]:
# predictions of to which cluster the observation belongs
predictions = census_clusters.fit_predict(census_missing[census_columns])
predictions

array([0, 0, 0, ..., 0, 0, 0], dtype=int32)

In [36]:
# distances to clusters for each observation
distances = census_clusters.fit_transform(census_missing[census_columns])
distances

array([[1.15570684e+04, 3.69620918e+06, 1.43820788e+07, 9.80336060e+05],
       [2.21082536e+05, 3.48566101e+06, 1.41718751e+07, 7.69443598e+05],
       [3.61264875e+04, 3.73912400e+06, 1.44248665e+07, 1.02362680e+06],
       ...,
       [4.86627601e+04, 3.74315726e+06, 1.44287543e+07, 1.02818398e+06],
       [3.99542806e+04, 3.72670429e+06, 1.44123218e+07, 1.01180662e+06],
       [3.87173975e+04, 3.72196223e+06, 1.44075840e+07, 1.00709323e+06]])

In [37]:
import numpy as np

# for those in cluster 1, the minimum distance is cluster 1 distance
distances[np.where(predictions == 1)[0]]

array([[ 5810320.38812675,  2106406.00976323,  8588496.98197191,
         4820695.36528671],
       [ 4476102.6537771 ,   772570.30820241,  9917118.44212282,
         3487047.05948377],
       [ 3214872.20101582,   513144.88932824, 11180977.9607949 ,
         2227802.42053226],
       [ 2917583.7319852 ,   803143.61151026, 11478171.47094131,
         1931074.32185437],
       [ 4650395.08966534,   949401.92658742,  9747031.09016275,
         3660815.51446326],
       [ 2639780.96926729,  1071684.93830065, 11753365.28587231,
         1652317.06398755],
       [ 2638751.07205886,  1068460.78265703, 11754836.98165016,
         1649246.11696707],
       [ 3698090.03048671,   142440.43241204, 10694584.7804203 ,
         2711662.69855657],
       [ 7638429.78822233,  3934192.92636933,  6766975.69819643,
         6648592.96931615],
       [ 2552577.53351075,  1178691.48062282, 11853030.30945281,
         1566122.04392865],
       [ 2896092.11175083,   811324.81306603, 11497340.39330611,
         1906916.11712856],
       [ 3674446.23633682,    90047.04032343, 10718559.38503944,
         2686172.70125791],
       [ 2399286.57048973,  1321620.17850686, 12001979.08062047,
         1410855.33953046],
       [ 3249793.55253301,   468570.83127775, 11142573.5974659 ,
         2262482.97835578],
       [ 2600881.4124259 ,  1106862.78904781, 11793283.22510292,
         1611394.38184193],
       [ 3496474.32744744,   256463.51530849, 10896520.35175075,
         2510180.71890551],
       [ 6174624.30715335,  2477104.8577661 ,  8220309.33559581,
         5187930.96349864],
       [ 2727572.35754429,   979151.11772729, 11665100.38549198,
         1738525.95452724],
       [ 3000730.75231106,   724533.29130056, 11398884.04900099,
         2011484.52919948]])

In [38]:
census_missing['Cluster'] = predictions

/home/ubuntu/.venvs/ironhack_env/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [41]:
census_missing[census_missing['Cluster'] == 2]

,CensusId,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,Asian,Pacific,Citizen,Income,IncomeErr,IncomePerCap,IncomePerCapErr,Poverty,ChildPoverty,Professional,Service,Office,Construction,Production,Drive,Carpool,Transit,Walk,OtherTransp,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment,Cluster
204,6037,California,Los Angeles,10038388,4945351,5093037,48.2,26.9,8.0,0.2,14.0,0.2,6046749,56196.0,270.0,28337,113,18.2,25.8,35.7,19.1,24.6,7.8,12.8,73.0,9.9,6.8,2.8,2.3,5.1,30.0,4635465,79.0,11.5,9.4,0.2,10.0,2

In [31]:
census_missing[census_missing.Cluster == 0].State.value_counts()

Texas             36
Ohio              36
North Carolina    34
New York          28
Georgia           26
Virginia          25
Wisconsin         23
Pennsylvania      23
Indiana           22
Michigan          22
Tennessee         22
Alabama           20
Kentucky          20
Oklahoma          18
Illinois          17
Missouri          16
Puerto Rico       15
Louisiana         14
Mississippi       13
Minnesota         13
Washington        13
West Virginia     12
Arkansas          12
Florida           11
South Carolina    11
Oregon            10
California        10
Iowa               9
New Mexico         7
Maryland           7
Kansas             5
Colorado           5
New Hampshire      5
Maine              5
Vermont            5
Montana            5
Idaho              4
Arizona            4
Nevada             4
Utah               4
Wyoming            4
New Jersey         3
Alaska             3
North Dakota       3
Nebraska           2
South Dakota       2
Rhode Island       2
Massachusetts      1
Hawaii             1
Name: State, dtype: int64

In [32]:
census_missing.groupby(['Cluster'])['Income'].mean()

Cluster
0     47811.923203
1     60623.000000
2     56196.000000
3     60551.271429
4     55251.000000
5     62949.836735
6     53580.307692
7     56483.600000
8     54343.000000
9     63891.882353
10    58411.826087
11    42861.669398
Name: Income, dtype: float64

## Silhoutte score

https://scikit-learn.org/stable/auto_examples/cluster/plot_kmeans_silhouette_analysis.html